"""Build the ED triage dashboard the same way any user would build theirs.

    python examples/build_ed_dashboard.py

This used to be a hand-written Streamlit app that happened to look like the
package's output. It is now generated by the package, which means the example
cannot drift from the library: if `write_dashboard` changes, this changes with
it, and if it breaks, this breaks loudly.

The data here is synthetic. Real UMN encounters cannot leave the institutional
computing environment, so the numbers this app shows are not model output and
must not be quoted. What is real is the shape: the same twelve variables, the
same nine outcomes, the same layout a reader would get from their own data.

To build the real thing, run the same script against real data:

    multidiseasepred train your_data.csv --targets outcome_ --out myapp
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from multidiseasepred import MultiDiseasePred

HERE = Path(__file__).parent
OUT = HERE / "ed_triage_dashboard"

# The twelve retained variables, in the order greedy forward selection picked
# them. Triage acuity is absent on purpose: it was excluded from the candidate
# set a priori, because the nurse's acuity score partly encodes the nurse's own
# judgement of the endpoints being predicted.
VARIABLES = [
    "age", "chiefcom_shortness_of_breath", "eci_PHTN", "triage_o2sat",
    "eci_FluidsLytes", "cci_MI", "cci_Pulmonary", "triage_dbp",
    "chiefcom_fever_chills", "triage_resprate", "triage_heartrate", "cci_Renal",
]

TARGETS = [
    "sepsis", "viral_pneumonia", "ards", "pulmonary_embolism",
    "copd_asthma_exacerbation", "acute_coronary_syndrome", "acute_kidney_injury",
    "hospitalization", "critical_outcome",
]

# Acute conditions and disposition are not the same kind of quantity: whether a
# condition is present depends on the patient, whether they are admitted also
# depends on whether there is a bed. They are macro-averaged separately.
GROUPS = {"acute conditions": TARGETS[:7], "disposition": TARGETS[7:]}

# Marginal distributions roughly matching the published cohort, so the widgets
# get sensible ranges. Continuous: (mean, sd). Binary: prevalence.
CONTINUOUS = {"age": (52, 21), "triage_o2sat": (97.5, 2.8),
              "triage_dbp": (78, 14), "triage_resprate": (18, 3.5),
              "triage_heartrate": (82, 17)}
BINARY = {"chiefcom_shortness_of_breath": 0.09, "eci_PHTN": 0.07,
          "eci_FluidsLytes": 0.29, "cci_MI": 0.07, "cci_Pulmonary": 0.22,
          "chiefcom_fever_chills": 0.06, "cci_Renal": 0.13}

# Signs follow the attribution pattern the trained model produced (eTable 14 of
# the manuscript). Low oxygen saturation and low diastolic pressure raise risk,
# so those weights are negative.
WEIGHTS = {
    "sepsis": {"eci_FluidsLytes": 0.52, "triage_dbp": -0.45, "age": 0.41,
               "triage_resprate": 0.27, "triage_o2sat": -0.24,
               "triage_heartrate": 0.23, "cci_Renal": 0.20,
               "chiefcom_fever_chills": 0.35},
    "viral_pneumonia": {"triage_o2sat": -0.47, "age": 0.44, "triage_dbp": -0.34,
                        "triage_resprate": 0.28,
                        "chiefcom_shortness_of_breath": 0.27,
                        "chiefcom_fever_chills": 0.20},
    "ards": {"triage_dbp": -0.73, "eci_FluidsLytes": 0.61, "triage_o2sat": -0.49,
             "age": 0.47, "triage_heartrate": 0.38, "triage_resprate": 0.33,
             "chiefcom_shortness_of_breath": 0.24},
    "pulmonary_embolism": {"eci_PHTN": 0.69, "triage_dbp": -0.47, "age": 0.44,
                           "triage_heartrate": 0.25, "eci_FluidsLytes": 0.22,
                           "triage_o2sat": -0.22},
    "copd_asthma_exacerbation": {"cci_Pulmonary": 1.20, "age": 0.40,
                                 "chiefcom_shortness_of_breath": 0.30,
                                 "triage_dbp": -0.29, "triage_o2sat": -0.28,
                                 "triage_resprate": 0.24},
    "acute_coronary_syndrome": {"age": 0.90, "cci_MI": 0.47,
                                "eci_FluidsLytes": 0.25, "cci_Renal": 0.20,
                                "triage_heartrate": 0.19, "triage_dbp": -0.17},
    "acute_kidney_injury": {"age": 0.66, "eci_FluidsLytes": 0.54,
                            "cci_Renal": 0.40, "triage_dbp": -0.27},
    "hospitalization": {"triage_dbp": -0.44, "eci_FluidsLytes": 0.36,
                        "age": 0.32, "triage_heartrate": 0.22,
                        "triage_o2sat": -0.16},
    "critical_outcome": {"eci_FluidsLytes": 0.50, "age": 0.36,
                              "triage_dbp": -0.30, "triage_o2sat": -0.27,
                              "triage_resprate": 0.23},
}

# Intercepts chosen so each outcome lands near its published prevalence.
BASE_RATE = {"sepsis": 0.027, "viral_pneumonia": 0.004, "ards": 0.001,
             "pulmonary_embolism": 0.007, "copd_asthma_exacerbation": 0.025,
             "acute_coronary_syndrome": 0.023, "acute_kidney_injury": 0.052,
             "hospitalization": 0.20, "critical_outcome": 0.009}


def synthesise(n=40_000, seed=42):
    rng = np.random.default_rng(seed)
    X = np.zeros((n, len(VARIABLES)), dtype=np.float32)
    for i, v in enumerate(VARIABLES):
        if v in CONTINUOUS:
            m, s = CONTINUOUS[v]
            X[:, i] = rng.normal(m, s, n)
        else:
            X[:, i] = (rng.random(n) < BINARY[v]).astype(np.float32)
    X[:, VARIABLES.index("age")] = np.clip(X[:, VARIABLES.index("age")], 18, 100)
    X[:, VARIABLES.index("triage_o2sat")] = np.clip(
        X[:, VARIABLES.index("triage_o2sat")], 60, 100)

    Z = (X - X.mean(0)) / np.where(X.std(0) == 0, 1, X.std(0))
    y = np.zeros((n, len(TARGETS)), dtype=int)
    for t, name in enumerate(TARGETS):
        lin = sum(w * Z[:, VARIABLES.index(v)] for v, w in WEIGHTS[name].items())
        # Solve the intercept so the simulated prevalence matches the real one.
        lo, hi = -20.0, 20.0
        for _ in range(60):
            mid = (lo + hi) / 2
            if (1 / (1 + np.exp(-(lin + mid)))).mean() < BASE_RATE[name]:
                lo = mid
            else:
                hi = mid
        y[:, t] = (rng.random(n) < 1 / (1 + np.exp(-(lin + (lo + hi) / 2)))).astype(int)
    return X, y


def main():
    X, y = synthesise()
    print(f"synthetic cohort: {len(X):,} encounters")
    for t, name in enumerate(TARGETS):
        print(f"    {name:<28} {y[:, t].sum():>7,}  ({y[:, t].mean():.2%})")

    model = MultiDiseasePred(variables=VARIABLES, targets=TARGETS, groups=GROUPS)
    # No selection step: these twelve *are* the retained set from the paper.
    # Run `select_variables` when you start from a wider candidate pool.
    print("\ntraining on synthetic data")
    model.fit(X, y, epochs=8, n_seeds=2)
    model.set_prevalence(y)

    model.write_dashboard(OUT, X=X, title="MultiDiseasePred — ED triage demo")
    banner = (
        "\n> **Synthetic demonstration.** This app was built by "
        "`examples/build_ed_dashboard.py` from simulated data, because the "
        "University of Minnesota encounters cannot leave the institution. The "
        "layout and the variables are real; the numbers are not model output "
        "and must not be quoted.\n")
    readme = OUT / "README.md"
    readme.write_text(readme.read_text() + banner)
    print(f"\nwritten to {OUT}/\n    streamlit run {OUT}/app.py")


if __name__ == "__main__":
    main()
