"""Generate a Streamlit dashboard for a fitted model.

    model.write_dashboard("myapp")
    streamlit run myapp/app.py

The app is written out as source rather than launched from inside the library,
because the thing you get should be yours: readable, editable, and deployable
without importing this package's opinions about layout. Everything specific to
your problem -- variable names, units, sensible ranges, target names, base rates
-- comes from the fitted model, so the app you get is about your outcomes and not
about ours.

Variable metadata is inferred from the training data when you pass it, and
falls back to something harmless when you do not. A column with two distinct
values becomes a checkbox; anything else becomes a number box with the observed
range. You can edit `variables.json` afterwards to add units and better labels
without touching the code.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import numpy as np

_APP = '''"""Dashboard for {title}.

Generated by multidiseasepred. Edit freely -- this file is yours.
Run with:  streamlit run app.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

from multidiseasepred import MultiDiseasePred

HERE = Path(__file__).parent
META = json.loads((HERE / "variables.json").read_text())

st.set_page_config(page_title={title!r}, layout="wide")


@st.cache_resource
def load():
    return MultiDiseasePred.load(HERE / "model")


model = load()
BASE = np.asarray(META["prevalence"], dtype=float) if META.get("prevalence") else None

st.title({title!r})
st.caption(
    "Calibrated risk for {n_targets} outcomes from {n_vars} inputs, in one pass. "
    "Research and decision-support use; not a substitute for clinical judgment."
)

with st.sidebar:
    st.header("Inputs")
    row = {{}}
    for v in META["variables"]:
        if v["kind"] == "binary":
            row[v["name"]] = 1.0 if st.checkbox(v["label"], value=bool(v["default"])) else 0.0
        else:
            row[v["name"]] = st.number_input(
                v["label"], value=float(v["default"]),
                min_value=float(v["min"]), max_value=float(v["max"]),
                step=float(v["step"]))

x = np.array([[row[v["name"]] for v in META["variables"]]], dtype=np.float32)
probs = model.predict(x)[0]

df = pd.DataFrame({{"outcome": model.targets, "risk": probs}})
if BASE is not None:
    df["base rate"] = BASE
    df["lift"] = df["risk"] / np.clip(BASE, 1e-9, None)
    df = df.sort_values("lift", ascending=False)
else:
    df = df.sort_values("risk", ascending=False)

left, right = st.columns([1, 1])
with left:
    st.subheader("Predicted risk")
    show = df.copy()
    show["risk"] = (show["risk"] * 100).map("{{:.2f}}%".format)
    if "base rate" in show:
        show["base rate"] = (show["base rate"] * 100).map("{{:.2f}}%".format)
        show["lift"] = show["lift"].map("{{:.1f}}x".format)
    st.dataframe(show, hide_index=True, use_container_width=True)
    if BASE is not None:
        st.caption(
            "Ordered by lift over each outcome's base rate, so a rare outcome "
            "is not buried under a common one. The calibrated probability is "
            "the primary number; lift is a comparison aid.")

with right:
    st.subheader("What moved this prediction")
    pick = st.selectbox("Outcome", df["outcome"].tolist())
    bg_path = HERE / "background.npy"
    if bg_path.exists():
        bg = np.load(bg_path)
        attr = model.explain(x[0], bg, n_samples=32)
        t = model.targets.index(pick)
        s = pd.Series(attr[t], index=model.active_variables)
        s = s.reindex(s.abs().sort_values(ascending=False).index).head(10)
        st.bar_chart(s)
        st.caption(
            "Expected-gradient attribution on the logit scale, for this "
            "encounter. Positive pushes risk up.")
    else:
        st.info("No background sample was saved, so attribution is unavailable. "
                "Pass `background=` to write_dashboard() to enable it.")
'''


def _infer(col: np.ndarray, name: str) -> dict:
    u = np.unique(col[~np.isnan(col)]) if col.dtype.kind == "f" else np.unique(col)
    label = name.replace("_", " ").strip().capitalize()
    if len(u) <= 2 and set(np.unique(u)).issubset({0.0, 1.0}):
        return {"name": name, "label": label, "kind": "binary",
                "default": 0, "min": 0, "max": 1, "step": 1}
    lo, hi = float(np.nanpercentile(col, 0.5)), float(np.nanpercentile(col, 99.5))
    med = float(np.nanmedian(col))
    span = max(hi - lo, 1e-6)
    step = 1.0 if span > 20 else (0.1 if span > 2 else 0.01)
    # Pad by a tenth so the widget allows values a little outside what was
    # observed, not by a whole span -- that produced negative ages and oxygen
    # saturations above 100. A quantity that is never negative in the training
    # data is treated as one that cannot be, which is the safer guess for the
    # physiological measurements these models are usually built on.
    pad = 0.1 * span
    vmin = lo - pad
    if float(np.nanmin(col)) >= 0:
        vmin = max(vmin, 0.0)
    return {"name": name, "label": label, "kind": "numeric",
            "default": round(med, 3), "min": round(vmin, 3),
            "max": round(hi + pad, 3), "step": step}


def write_dashboard(model, path, *, X: Optional[np.ndarray] = None,
                    background: Optional[np.ndarray] = None,
                    title: str = "MultiDiseasePred", n_background: int = 200):
    """Write a runnable Streamlit app for `model` into `path`.

    Parameters
    ----------
    X
        Training rows, used only to infer sensible defaults and ranges for the
        input widgets. Without it the widgets fall back to 0-1 ranges, which
        work but will look wrong for anything measured in mmHg.
    background
        Rows used as the reference distribution for attribution. Defaults to a
        sample of `X`. Without either, the app runs and predicts but cannot
        explain.
    """
    out = Path(path)
    out.mkdir(parents=True, exist_ok=True)
    names = model.active_variables

    if X is not None:
        Xa = np.asarray(X, dtype=float)
        if Xa.shape[1] == len(model.variables) and names != model.variables:
            Xa = Xa[:, [model.variables.index(v) for v in names]]
        meta_vars = [_infer(Xa[:, i], n) for i, n in enumerate(names)]
    else:
        meta_vars = [{"name": n, "label": n.replace("_", " ").capitalize(),
                      "kind": "numeric", "default": 0, "min": 0, "max": 1,
                      "step": 0.01} for n in names]

    prev = getattr(model, "prevalence_", None)
    meta = {"variables": meta_vars, "targets": model.targets,
            "prevalence": list(map(float, prev)) if prev is not None else None}
    (out / "variables.json").write_text(json.dumps(meta, indent=2))

    bg = background if background is not None else X
    if bg is not None:
        bg = np.asarray(bg, dtype=np.float32)
        if bg.shape[1] == len(model.variables) and names != model.variables:
            bg = bg[:, [model.variables.index(v) for v in names]]
        rng = np.random.default_rng(model.seed)
        take = rng.choice(len(bg), min(n_background, len(bg)), replace=False)
        np.save(out / "background.npy", bg[take])

    model.save(out / "model")
    (out / "app.py").write_text(_APP.format(
        title=title, n_targets=len(model.targets), n_vars=len(names)))
    (out / "requirements.txt").write_text(
        "streamlit>=1.30\nnumpy\npandas\nscikit-learn\ntorch\nmultidiseasepred\n")
    (out / "README.md").write_text(
        f"# {title}\n\n"
        f"Generated by multidiseasepred from a fitted model with "
        f"{len(names)} inputs and {len(model.targets)} outcomes.\n\n"
        "```bash\npip install -r requirements.txt\nstreamlit run app.py\n```\n\n"
        "`variables.json` controls the input widgets. Edit the labels, units, "
        "defaults and ranges there; the app reads them at startup and nothing "
        "in `app.py` needs to change.\n")
    return out
