"""Dashboard for MultiDiseasePred — ED triage demo.

Generated by multidiseasepred. Edit freely -- this file is yours.
Run with:  streamlit run app.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

from multidiseasepred import MultiDiseasePred

HERE = Path(__file__).parent
META = json.loads((HERE / "variables.json").read_text())

st.set_page_config(page_title='MultiDiseasePred — ED triage demo', layout="wide")


@st.cache_resource
def load():
    return MultiDiseasePred.load(HERE / "model")


model = load()
BASE = np.asarray(META["prevalence"], dtype=float) if META.get("prevalence") else None

st.title('MultiDiseasePred — ED triage demo')
st.caption(
    "Calibrated risk for 9 outcomes from 12 inputs, in one pass. "
    "Research and decision-support use; not a substitute for clinical judgment."
)

with st.sidebar:
    st.header("Inputs")
    row = {}
    for v in META["variables"]:
        if v["kind"] == "binary":
            row[v["name"]] = 1.0 if st.checkbox(v["label"], value=bool(v["default"])) else 0.0
        else:
            row[v["name"]] = st.number_input(
                v["label"], value=float(v["default"]),
                min_value=float(v["min"]), max_value=float(v["max"]),
                step=float(v["step"]))

x = np.array([[row[v["name"]] for v in META["variables"]]], dtype=np.float32)
probs = model.predict(x)[0]

df = pd.DataFrame({"outcome": model.targets, "risk": probs})
if BASE is not None:
    df["base rate"] = BASE
    df["lift"] = df["risk"] / np.clip(BASE, 1e-9, None)
    df = df.sort_values("lift", ascending=False)
else:
    df = df.sort_values("risk", ascending=False)

left, right = st.columns([1, 1])
with left:
    st.subheader("Predicted risk")
    show = df.copy()
    show["risk"] = (show["risk"] * 100).map("{:.2f}%".format)
    if "base rate" in show:
        show["base rate"] = (show["base rate"] * 100).map("{:.2f}%".format)
        show["lift"] = show["lift"].map("{:.1f}x".format)
    st.dataframe(show, hide_index=True, use_container_width=True)
    if BASE is not None:
        st.caption(
            "Ordered by lift over each outcome's base rate, so a rare outcome "
            "is not buried under a common one. The calibrated probability is "
            "the primary number; lift is a comparison aid.")

with right:
    st.subheader("What moved this prediction")
    pick = st.selectbox("Outcome", df["outcome"].tolist())
    bg_path = HERE / "background.npy"
    if bg_path.exists():
        bg = np.load(bg_path)
        attr = model.explain(x[0], bg, n_samples=32)
        t = model.targets.index(pick)
        s = pd.Series(attr[t], index=model.active_variables)
        s = s.reindex(s.abs().sort_values(ascending=False).index).head(10)
        st.bar_chart(s)
        st.caption(
            "Expected-gradient attribution on the logit scale, for this "
            "encounter. Positive pushes risk up.")
    else:
        st.info("No background sample was saved, so attribution is unavailable. "
                "Pass `background=` to write_dashboard() to enable it.")
